package th.co.dv.p2p.corda.base.models

/**
 * Search Model For Credit Note to enable the front end to query By:-
 * the fields available inside this state
 */
data class CreditNoteSearchModel (
        val documentEntryDateFrom: String? = null,
        val documentEntryDateTo: String? = null,
        val statuses: List<String>? = null,
        val linearIds: List<String>? = null,
        val invoiceExternalId: String? = null,
        val vendorName: String? = null,
        val vendorNumber: String? = null,
        val vendorTaxNumber: String? = null,
        val companyCode: String? = null,
        val companyName: String? = null,
        val companyTaxNumber: String? = null,
        val creditNoteDateFrom: String? = null,
        val creditNoteDateTo: String? = null,
        val creditNotePostingDateFrom: String? = null,
        val creditNotePostingDateTo: String? = null,
        val isNormalSubtype: Boolean? = null,
        val exactCreditNoteBuyerPostingDate: String? = null,
        val excludeRejectedOtherType: Boolean? = null,
        val creditNoteExternalId: String? = null,
        val creditPostingUpdatedDate: String? = null,
        val invoiceNumber: String? = null,
        val isSellerStatus: Boolean = false,
        val returnPurchases: Boolean = false,
        val returnGoodsReceiveds: Boolean = false,
        val returnInvoiceItems: Boolean = false,
        val returnInvoice: Boolean = false,
        val returnCreditNoteItems: Boolean = true,
        val lifecycles: List<String>? = null,
        val postingStatus: List<String>? = null,
        val postingStatusNotIn: List<String>? = null,
        val invoiceLinearId: List<String>? = null,
        val purchaseOrderNumber: List<String>? = null,
        val purchaseItemLinearId: List<String>? = null,
        val adjustmentType: List<String>? = null,
        val goodsReceivedExternalId: List<String>? = null,
        val matchingDateFrom: String? = null,
        val matchingDateTo: String? = null,
        val sortField: String = "externalId",
        val sortOrder: Int = 1,
        val pageNumber: Int = 1,
        val pageSize: Int = 500,
        val isIssuePayment: Boolean? = null,
        val referenceField1: String? = null,
        val paymentDateFrom: String? = null,
        val paymentDateTo: String? = null,
        val paymentItemLinearIds: List<String>? = null,
        val returnBuyerPostingDetail: Boolean = false,
        val companyTaxNumbers: List<String>? = null,
        val vendorTaxNumbers: List<String>? = null,
        val returnPoNumber: Boolean = false,
        val returnGrNumber: Boolean = false,
        val items: Boolean = false,
        val buyerApprovedDateFrom: String? = null,
        val buyerApprovedDateTo: String? = null,
        val lastMatchUpdatedDateFrom: String? = null,
        val lastMatchUpdatedDateTo: String? = null,
        val buyerPostingDateFrom: String? = null,
        val buyerPostingDateTo: String? = null,
        val isRdSubmitted: Boolean? = null,
        val vatTriggerPoints: List<String>? = null,
        val taxDocumentLinearIds : List<String>? = null,
        val taxDocumentNumber: String? = null,
        val taxDocumentLinearIdIsNull: Boolean? = null,
        val isOnHold: Boolean? = null,
        val paymentDescription: String? = null,
        val creditNoteSubType: String? = null,
        val contractNumber: String? = null,
        val returnRelatedData: Boolean? = null
)