package th.co.dv.p2p.corda.base.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import net.corda.core.serialization.CordaSerializable
import th.co.dv.p2p.common.models.BuyerVendorPKModel

/**
 * @property invoicePendingGoodsPeriods is the length of days where invoice is pending goods i.e "7,15,30,200000"
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@CordaSerializable
@JsonInclude(JsonInclude.Include.NON_NULL)
data class InvoiceSearchModel(
        val statuses: List<String>? = null,
        val invoiceNumber: String? = null,
        val invoiceLinearId: String? = null,
        val purchaseOrderNumber: String? = null,
        val goodsReceivedNumber: String? = null,
        val invoiceDateFrom: String? = null,
        val invoiceDateTo: String? = null,
        val invoiceEntryDateFrom: String? = null,
        val invoiceEntryDateTo: String? = null,
        val matchingDateFrom: String? = null,
        val matchingDateTo: String? = null,
        val dueDateFrom: String? = null,
        val dueDateTo: String? = null,
        val companyName: String? = null,
        val vendorCode: String? = null,
        val site: String? = null,
        val section: String? = null,
        val pageNumber: Int = 1,
        val pageSize: Int = 500,
        val sortField: String = "externalId",
        val sortOrder: Int = 1,
        val returnInvoiceItems: Boolean = false,
        val isSellerStatus: Boolean = true,
        val accountingApproved: Boolean? = null,
        val buyerApproved: Boolean? = null,
        val resubmitCountFrom: Int? = null,
        val resubmitCountTo: Int? = null,
        val postingStatus: List<String>? = null,
        val postingStatusNotIn: List<String>? = null,
        val lifecycleNotIn: List<String>? = null,
        val bankIsAdded: Boolean? = null,
        val calculatedDateIsAdded: Boolean? = null,
        val vendorName: String? = null,
        val invoicePostingIsUpdatedDateFrom: String? = null,
        val invoicePostingIsUpdatedDateTo: String? = null,
        val exactInvoiceBuyerPostingDate: String? = null,
        val currentAuthority: List<String>? = null,
        val unmatchedReasonIsNull: Boolean? = null,
        val unmatchedReason: String? = null,
        val businessPlace: String? = null,
        val companyCode: String? = null,
        val companyCodes: List<String>? = null,
        val vendorNames: List<String?>? = null,
        val vendorCodes: List<String?>? = null,
        val invoiceNumbers: List<String?>? = null,
        val currency: String? = null,
        val vendorBranchName: String? = null,
        val vendorTelephone: String? = null,
        val companyTelephone: String? = null,
        val referenceField1: String? = null,
        val referenceField2: String? = null,
        val referenceField3: String? = null,
        val referenceField4: String? = null,
        val referenceField5: String? = null,
        val lastMatchUpdatedDateFrom: String? = null,
        val lastMatchUpdatedDateTo: String? = null,
        val linearIds: List<String>? = null,
        val invoicePendingGoodsPeriods: String? = null,
        val isNormalSubtype: Boolean? = null,
        val isOnHold: Boolean? = null,
        val isAutoMatched: Boolean? = null,
        val isInvoiceFinancing: Boolean? = null,
        val isMatched: Boolean? = null,
        val vendorTaxNumber: String? = null,
        val isIssuePayment: Boolean? = null,
        val dashboardType: String? = null,
        val exactlyInvoiceNumber: String? = null,
        val invoiceItemsLinearId: List<String>? = null,
        val companyTaxNumber: String? = null,
        val exactlyGoodsReceivedNumber: String? = null,
        val ignoreZeroPayableAmount: Boolean? = null,
        val dueDateIsLocked: Boolean? = null,
        val customIndicator1: Boolean? = null,
        val lifecycles: List<String>? = null,
        val lifecyclesNotIn: List<String>? = null,
        val paymentItemLinearIds: List<String>? = null,
        val paymentItemLinearId: String? = null,
        val withCompanyAndVendorTaxNumbers: List<Pair<String, String>>? = null,
        val itemReferenceField1: String? = null,
        val itemReferenceField2: String? = null,
        val itemReferenceField3: String? = null,
        val itemReferenceField4: String? = null,
        val itemReferenceField5: String? = null,
        val vatTransferStatus: List<String>? = null,
        val vatTransferStatusNotIn: List<String>? = null,
        val invoiceVatTransferIsUpdatedDateFrom: String? = null,
        val invoiceVatTransferIsUpdatedDateTo: String? = null,
        val buyerPostingDateFrom: String? = null,
        val buyerPostingDateTo: String? = null,
        val username: String? = null,
        val companyTaxNumbers: List<String>? = null,
        val vendorTaxNumbers: List<String>? = null,
        val returnBuyerPostingDetail: Boolean = false,
        val returnCurrentAuthority: Boolean = false,
        val returnTotalRecords: Boolean = true,
        val returnGrItems: Boolean = false,
        val returnRelatedData: Boolean? = null,
        val isRdSubmitted: Boolean? = null,
        val subtypeNotIn: List<String>? = null,
        val materialGroup: String? = null,
        val materialNumber: String? = null,
        val withholdingTaxCode: String? = null,
        val approvedDateFrom: String? = null,
        val approvedDateTo: String? = null,
        val vatTriggerPoints: List<String>? = null,
        val taxDocumentLinearIds : List<String>? = null,
        val taxDocumentNumber: String? = null,
        val taxDocumentLinearIdIsNull: Boolean? = null,
        val yearByInvoiceDate: String? = null,
        val inactiveSuppliers: List<BuyerVendorPKModel>? = null,
        val returnValidationList: Boolean = false,
        val paymentDescription: String? = null,
        val isDocumentValidation: Boolean = false,
        val isService: Boolean? = null,
        val paymentDateFrom: String? = null,
        val paymentDateTo: String? = null,
        val lastHeldBy: String? = null,
        val waitingReceiptExcludeTaxDoc: Boolean? = null,
        val invoiceFinancedDateFrom: String? = null,
        val invoiceFinancedDateTo: String? = null
)
