server:
  port: ${PORT}

spring:
  main.allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379


logging:
  level:
    th.co.dv: INFO
    org.hibernate.SQL: DEBUG


line.bot:
  channel-token: ${LINE_TOKEN}
  channel-secret: ${LINE_SECRET}
  handler.path: /callback
  baseUrl: https://api.line.me/v2/

chat:
  apiKey: ${CHAT_API_KEY}