line.bot:
  channel-token: 'cwJTpfEgbIGRszTR2bhMH/a+yqyU0QhjD5OzJ6CDlS5BzZ47u/zol4uIocku9wAQSkMSOrnEsE2chVEJt5VL7hwlZy9chRDSUXLdPiXpLK2L4T7dzrHMYsSUWglXW7SEhyHW/yKaoIWNaEqStZV3UAdB04t89/1O/w1cDnyilFU='
  channel-secret: 'f48eaac5b0fbb026c66ebd9a4dd1961b'
  handler.path: /callback
  baseUrl: https://api.line.me/v2/
  broadcaster:
    OAT: Ud6ea1a3aaf44201a7ab7ee1e500f2d79
    OHM: U080295aaad0b3bcb412ff0b82093c61b

subscription:
  path: /Users/jittawat.t/Desktop/subscription.csv

friend:
  path: /Users/jittawat.t/Desktop/friends.csv

squad:
  path: /Users/jittawat.t/Desktop/squad_updated.xlsx