line.bot:
  channel-token: '2NdhgLNW6+jK3YZrO1kcE2lnjhu87cnCL8coEk/VWKhxlHiagjCYvGZlkFV0V3VIleII7P7dhgCscgrYBm9MGWwJ7qk8mS7GuG2r/Taejo5iShxigsakbsree+/lUVxLl9D2iU6g089yjVGtSVQMnAdB04t89/1O/w1cDnyilFU='
  channel-secret: '3b53afc7b0f87d49a1f1ab693075817c'
  handler.path: /callback

subscription:
  path: /Users/jittawat.t/Desktop/subscription.csv