package th.co.dv.p2p.common.utilities.manager

import th.co.dv.p2p.common.utilities.copyPropsFrom
import th.co.dv.p2p.corda.base.domain.Quantity
import th.co.dv.p2p.corda.base.models.PartyModel
import th.co.dv.p2p.corda.base.models.PurchaseItemModel
import java.math.BigDecimal
import java.util.*

/**
 * This entity is mock implementation for InterfaceBasePurchaseItem
 */
data class MockPurchaseItem(
        override val accountCode: String? = null,
        override val accountCodeDescription: String? = null,
        override val poNumber: String? = null,
        override val accountAssignment: String? = null,
        override val buyer: PartyModel? = null,
        override val businessPlace: String? = null,
        override val businessPlaceTaxNumber: String? = null,
        override val businessPlaceOrganization: String? = null,
        override val businessPlaceDescription: String? = null,
        override val businessPlaceName1: String? = null,
        override val businessPlaceName2: String? = null,
        override val businessPlaceName3: String? = null,
        override val businessPlaceName4: String? = null,
        override val businessPlaceStreet1: String? = null,
        override val businessPlaceStreet2: String? = null,
        override val businessPlaceStreet3: String? = null,
        override val businessPlaceStreet4: String? = null,
        override val businessPlaceStreet5: String? = null,
        override val businessPlaceCity: String? = null,
        override val businessPlaceDistrict: String? = null,
        override val businessPlacePostalCode: String? = null,
        override val businessPlacePostalTelephone: String? = null,
        override val businessPlaceCountry: String? = null,
        override val businessPlaceDepartment: String? = null,
        override val businessPlaceEmail: String? = null,
        override val businessPlaceOfficerName: String? = null,
        override val businessPlaceOfficerEmail: String? = null,
        override val businessPlaceOfficerTelephone: String? = null,
        override val customisedFields: Map<String, Any> = emptyMap(),
        override val customisedFieldsUpdatedDate: Date? = null,
        override val companyCode: String? = null,
        override val companyBranchCode: String? = null,
        override val companyName: String? = null,
        override val calendarKey: String? = null,
        override val costCenter: String? = null,
        override val costCenterDescription: String? = null,
        override val costType: String? = null,
        override val costTypeDescription: String? = null,
        override val documentEntryDate: Date? = null,
        override val deliveryStatus: String? = null,
        override val deleteFlag: String? = null,
        override val expectedDeliveryDate: Date? = null,
        override val estimatedUnitPrice: String? = null,
        override val freeItemIndicator: String? = null,
        override val issuedDate: Date? = null,
        override val itemCategory: String? = null,
        override val invoiceList: String? = null,
        override val lastConfirmedBy: String? = null,
        override val lastConfirmedDate: Date? = null,
        override val lastPartyConfirmedBy: PartyModel? = null,
        override val lastPartyUpdatedBy: PartyModel? = null,
        override val lastUpdatedBy: String? = null,
        override val lastUpdatedDate: Date? = null,
        override val lifecycle: String? = null,
        override val linearId: String? = UUID.randomUUID().toString(),
        override val materialDescription: String? = null,
        override val materialNumber: String? = null,
        override val materialGroup: String? = null,
        override val overDeliveryTolerance: BigDecimal? = null,
        override val overDeliveryQuantity: Quantity? = null,
        override val paymentTermDescription: String? = null,
        override val purchasingOrg: String? = null,
        override val purchasingGroupName: String? = null,
        override val purchasingGroupTel: String? = null,
        override val purchasingEmail: String? = null,
        override val purchaseOrderLinearId: String? = null,
        override val plantDescription: String? = null,
        override val paymentTermCode: String? = null,
        override val paymentTermDays: Long? = null,
        override val purchaseRequestNumber: String? = null,
        override val purchaseRequestItem: String? = null,
        override val purchasingGroup: String? = null,
        override val poItemNo: String? = null,
        override val poItemUnitPrice: BigDecimal? = null,
        override val poItemUnitPriceCurrency: String? = null,
        override val quantity: Quantity? = null,
        override val poItemDeliveryDate: Date? = null,
        override val proposedRevisedDeliveryDate: Date? = null,
        override val initialDeliveryDate: Date? = null,
        override val referenceField1: String? = null,
        override val referenceField2: String? = null,
        override val referenceField3: String? = null,
        override val referenceField4: String? = null,
        override val referenceField5: String? = null,
        override val revisedDeliveryDate: Date? = null,
        override val revisedReason: String? = null,
        override val section: String? = null,
        override val sectionDescription: String? = null,
        override var status: String? = null,
        override val site: String? = null,
        override val siteDescription: String? = null,
        override val seller: PartyModel? = null,
        override val taxCode: String? = null,
        override val taxRate: BigDecimal? = null,
        override val timeZone: String? = null,
        override val unitDescription: String? = null,
        override val underDeliveryTolerance: BigDecimal? = null,
        override val vatTriggerPoint: String? = null,
        override val vendorNumber: String? = null,
        override val vendorTaxNumber: String? = null,
        override val vendorEmail: String? = null,
        override val vendorBranchCode: String? = null,
        override val vendorBranchName: String? = null,
        override val vendorCountry: String? = null,
        override val vendorDepartment: String? = null,
        override val vendorName: String? = null,
        override val vendorName2: String? = null,
        override val vendorName3: String? = null,
        override val vendorName4: String? = null,
        override val vendorStreet1: String? = null,
        override val vendorStreet2: String? = null,
        override val vendorStreet3: String? = null,
        override val vendorStreet4: String? = null,
        override val vendorStreet5: String? = null,
        override val vendorCity: String? = null,
        override val vendorDistrict: String? = null,
        override val vendorOrganization: String? = null,
        override val vendorPostalCode: String? = null,
        override val vendorTelephone: String? = null,
        override val vendorOfficerName: String? = null,
        override val vendorOfficerEmail: String? = null,
        override val vendorOfficerTelephone: String? = null,
        override val withholdingTaxIncomeType: String? = null,
        override val withholdingTaxIncomeDescription: String? = null,
        override val withholdingTaxPercent: BigDecimal? = null,
        override val withholdingTaxCode: String? = null,
        override val withholdingTaxDescription: String? = null,
        override val withholdingTaxCalculationPoint: String? = null,
        override val taxDescription: String? = null,
        override val requesterEmail: String? = null,
        override val requesterName: String? = null,
        override val contractNumber: String? = null,
        override val amount: BigDecimal? = null,
        override val remainingAmount: BigDecimal? = null,
        override val consumedAmount: BigDecimal? = null,
        override val effectiveDate: Date? = null,
        override val advanceInitialAmount: BigDecimal? = null,
        override val advancePaymentRemainingAmount: BigDecimal? = null,
        override val advancePaymentToBeDeducted: BigDecimal? = null,
        override val paymentDueDate: Date? = null
) : InterfaceBasePurchaseItem {
    override fun toModel(searchModel: Any): Any {
        return this.toPurchaseItemModel()
    }
}


/**
 * Method for convert purchase item entity to model
 */
fun MockPurchaseItem.toPurchaseItemModel(): PurchaseItemModel {
    val purchaseItemModel = PurchaseItemModel()
    purchaseItemModel.copyPropsFrom(this)
    return purchaseItemModel.copy(
            externalId = poItemNo
    )
}