package th.co.dv.p2p.common.utilities.manager

import th.co.dv.p2p.corda.base.domain.Quantity
import th.co.dv.p2p.corda.base.models.PartyModel
import java.math.BigDecimal
import java.util.*

interface InterfaceBasePurchaseItem : ModelableEntity {
        val accountCode: String?
        val accountCodeDescription: String?
        val poNumber: String?
        val accountAssignment: String?
        val buyer: PartyModel?
        val businessPlace: String?
        val businessPlaceTaxNumber: String?
        val businessPlaceOrganization: String?
        val businessPlaceDescription: String?
        val businessPlaceName1: String?
        val businessPlaceName2: String?
        val businessPlaceName3: String?
        val businessPlaceName4: String?
        val businessPlaceStreet1: String?
        val businessPlaceStreet2: String?
        val businessPlaceStreet3: String?
        val businessPlaceStreet4: String?
        val businessPlaceStreet5: String?
        val businessPlaceCity: String?
        val businessPlaceDistrict: String?
        val businessPlacePostalCode: String?
        val businessPlacePostalTelephone: String?
        val businessPlaceCountry: String?
        val businessPlaceDepartment: String?
        val businessPlaceEmail: String?
        val businessPlaceOfficerName: String?
        val businessPlaceOfficerEmail: String?
        val businessPlaceOfficerTelephone: String?
        val customisedFields: Map<String, Any>
        val customisedFieldsUpdatedDate: Date?
        val companyCode: String?
        val companyBranchCode: String?
        val companyName: String?
        val calendarKey: String?
        val costCenter: String?
        val costCenterDescription: String?
        val costType: String?
        val costTypeDescription: String?
        val documentEntryDate: Date?
        val deliveryStatus: String?
        val deleteFlag: String?
        val expectedDeliveryDate: Date?
        val estimatedUnitPrice: String?
        val freeItemIndicator: String?
        val issuedDate: Date?
        val itemCategory: String?
        val invoiceList: String?
        val lastConfirmedBy: String?
        val lastConfirmedDate: Date?
        val lastPartyConfirmedBy: PartyModel?
        val lastPartyUpdatedBy: PartyModel?
        val lastUpdatedBy: String?
        val lastUpdatedDate: Date?
        val lifecycle: String?
        val linearId: String?
        val materialDescription: String?
        val materialNumber: String?
        val materialGroup: String?
        val overDeliveryTolerance: BigDecimal?
        val overDeliveryQuantity: Quantity?
        val paymentTermDescription: String?
        val purchasingOrg: String?
        val purchasingGroupName: String?
        val purchasingGroupTel: String?
        val purchasingEmail: String?
        val purchaseOrderLinearId: String?
        val plantDescription: String?
        val paymentTermCode: String?
        val paymentTermDays: Long?
        val purchaseRequestNumber: String?
        val purchaseRequestItem: String?
        val purchasingGroup: String?
        val poItemNo: String?
        val poItemUnitPrice: BigDecimal?
        val poItemUnitPriceCurrency: String?
        val quantity: Quantity?
        val poItemDeliveryDate: Date?
        val proposedRevisedDeliveryDate: Date?
        val initialDeliveryDate: Date?
        val referenceField1: String?
        val referenceField2: String?
        val referenceField3: String?
        val referenceField4: String?
        val referenceField5: String?
        val revisedDeliveryDate: Date?
        val revisedReason: String?
        val section: String?
        val sectionDescription: String?
        var status: String?
        val site: String?
        val siteDescription: String?
        val seller: PartyModel?
        val taxCode: String?
        val taxRate: BigDecimal?
        val timeZone: String?
        val unitDescription: String?
        val underDeliveryTolerance: BigDecimal?
        val vatTriggerPoint: String?
        val vendorNumber: String?
        val vendorTaxNumber: String?
        val vendorEmail: String?
        val vendorBranchCode: String?
        val vendorBranchName: String?
        val vendorCountry: String?
        val vendorDepartment: String?
        val vendorName: String?
        val vendorName2: String?
        val vendorName3: String?
        val vendorName4: String?
        val vendorStreet1: String?
        val vendorStreet2: String?
        val vendorStreet3: String?
        val vendorStreet4: String?
        val vendorStreet5: String?
        val vendorCity: String?
        val vendorDistrict: String?
        val vendorOrganization: String?
        val vendorPostalCode: String?
        val vendorTelephone: String?
        val vendorOfficerName: String?
        val vendorOfficerEmail: String?
        val vendorOfficerTelephone: String?
        val withholdingTaxIncomeType: String?
        val withholdingTaxIncomeDescription: String?
        val withholdingTaxPercent: BigDecimal?
        val withholdingTaxCode: String?
        val withholdingTaxDescription: String?
        val withholdingTaxCalculationPoint: String?
        val taxDescription: String?
        val requesterEmail: String?
        val requesterName: String?
        val contractNumber: String?
        val amount: BigDecimal?
        val remainingAmount: BigDecimal?
        val consumedAmount: BigDecimal?
        val effectiveDate: Date?
        val advanceInitialAmount: BigDecimal?
        val advancePaymentRemainingAmount: BigDecimal?
        val advancePaymentToBeDeducted: BigDecimal?
        val paymentDueDate: Date?
}